# Generated by Django 5.0 on 2023-12-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_deposit_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_balance',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
