# Generated by Django 5.0 on 2023-12-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_account_balance_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='borrowing',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.DeleteModel(
            name='Borrowing',
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
