# Generated by Django 5.0 on 2023-12-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
