# Generated by Django 5.0 on 2024-01-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_category_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
    ]
