# Generated by Django 5.0 on 2023-12-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BORROW', 'Borrow'), ('RETURN', 'Return')], max_length=10),
        ),
    ]
