# Generated by Django 5.0 on 2023-12-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
