# Generated by Django 5.0 on 2024-01-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_transaction_user_transaction_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='returned',
            new_name='is_returned',
        ),
    ]
