# Generated by Django 5.0 on 2024-01-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_returned_transaction_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'Deposite'), (2, 'Borrow Book'), (3, 'Return Book')], max_length=10),
        ),
    ]
